-- Script SQL para criar a tabela no Supabase SQL Editor
-- Tabela: sinais_forex

create table if not exists public.sinais_forex (
    id bigint generated by default as identity primary key,
    pair text not null unique,               -- Ex: "EUR/USD", "GBP/USD", "USD/JPY"
    current_price numeric(12, 5) not null,   -- Preço atual de mercado
    signal text not null,                    -- "BUY", "SELL" ou "NEUTRO"
    tendency text not null,                  -- "Alta", "Baixa" ou "Lateral"
    probability integer not null,            -- Ex: 85 (85%)
    signal_strength text not null,           -- "Força Alta", "Força Média", "Neutra"
    entry_price numeric(12, 5) not null,     -- Preço recomendado de entrada
    stop_loss numeric(12, 5) not null,       -- Preço de Stop Loss
    take_profit numeric(12, 5) not null,     -- Preço de Take Profit 1
    take_profit_2 numeric(12, 5),            -- Preço de Take Profit 2 (opcional)
    risk_reward text not null,               -- Ex: "1 : 1.85"
    timeframe text not null default '1h',    -- Intervalo analisado ('1h')
    ema_50 numeric(12, 5),                   -- Valor da EMA de 50 períodos
    rsi_14 numeric(6, 2),                    -- Valor do RSI (14)
    macd_val numeric(12, 5),                 -- Linha MACD
    macd_signal numeric(12, 5),              -- Linha de Sinal do MACD
    macd_hist numeric(12, 5),                -- Histograma do MACD
    ai_analysis text,                        -- Texto explicativo gerado pela regra/IA
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Criar índice para buscas rápidas por par de moedas
create index if not exists idx_sinais_forex_pair on public.sinais_forex (pair);

-- Habilitar Row Level Security (RLS)
alter table public.sinais_forex enable row level security;

-- Política de leitura pública (permite que o frontend PWA leia os sinais)
create policy "Leitura pública de sinais" 
on public.sinais_forex 
for select 
using (true);

-- Política de inserção/atualização para chaves de serviço ou usuários autenticados
create policy "Atualização via backend/service_role" 
on public.sinais_forex 
for all 
using (true)
with check (true);
